# Generated by Django 4.0.1 on 2022-01-22 10:44

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('publisher', models.CharField(max_length=1000)),
                ('edition', models.DecimalField(decimal_places=2, default=18.0, max_digits=20)),
                ('book_img', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='book_images/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
